Exercicio1 

In [17]:
import numpy as np
#Variando de 1 a 7 
array1 = np.random.randint(1, 7, size=(np.random.randint(1, 7), np.random.randint(1, 7)))
print(array1.shape)
print('-----')
mult = array1.shape[0] * array1.shape[1]
print(mult)
print('-----')
if mult % 2 == 0:
    print('A matriz pode ser transformada em um vetor par')
else:
    print('A matriz pode ser transformada em um vetor ímpar')


(1, 6)
-----
6
-----
A matriz pode ser transformada em um vetor par


In [21]:
np.random.seed(10)

matriz = np.random.randint(1, 51, size=(4, 4))
print("Matriz Gerada:")
print(matriz)

media_linhas = np.mean(matriz, axis=1)  
media_colunas = np.mean(matriz, axis=0)  
print("\nMédia de cada linha:")
print(media_linhas)
print("\nMédia de cada coluna:")
print(media_colunas)


maior_media_linhas = np.max(media_linhas)
maior_media_colunas = np.max(media_colunas)
print("\nMaior valor das médias das linhas:", maior_media_linhas)
print("Maior valor das médias das colunas:", maior_media_colunas)


unique, counts = np.unique(matriz, return_counts=True)
aparicoes = dict(zip(unique, counts))

numeros_2_vezes = {k: v for k, v in aparicoes.items() if v == 2}
print("\nNúmeros que aparecem 2 vezes:")
print(numeros_2_vezes)

Matriz Gerada:
[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]

Média de cada linha:
[16.   33.75 34.5  23.75]

Média de cada coluna:
[29.75 24.25 33.75 20.25]

Maior valor das médias das linhas: 34.5
Maior valor das médias das colunas: 33.75

Números que aparecem 2 vezes:
{np.int32(1): np.int64(2), np.int32(10): np.int64(2), np.int32(30): np.int64(2), np.int32(50): np.int64(2)}
